### ISSUE TITLE
setTimeout doesn't clamp to 1ms by default

### ISSUE THREAD

**Issue by smaug----** [WICG/scheduling-apis#1]
See step 10
https://html.spec.whatwg.org/#timers:dom-setinterval-7

**Comment by spanicker** [comment]
Thanks Olli, I've clarified "in Chrome".
Curious - does FF do any clamping on settimeout / setinterval?

**Comment by smaug----** [comment]
FF uses the clamping the spec defines, see step 11 in the algorithm.

**Comment by shaseley** [comment]
I'm doing a pass through the open issues and I found another instance of this text in an old document in the repo; fixed [here](https://github.com/WICG/scheduling-apis/commit/3c8ca43434aadaa63ed77f298d747632050b2ddb). Closing this out now as the text has been clarified.

FYI there is [work being done](https://groups.google.com/a/chromium.org/g/blink-dev/c/HKPTp7C1LwY/m/kIbTxKSPAwAJ) to remove the 1 ms clamping in Chromium.
