### ISSUE TITLE
Why does the yield task block the scroll event appear in the later stage of fast scrolling?

### ISSUE THREAD

**Issue by huangruiqi** [WICG/scheduling-apis#101]
<img width="1341" alt="image" src="https://github.com/user-attachments/assets/7dce005c-9dce-4e65-a246-2b0aa3a51b3f">
Why does the yield task block the scroll event appear in the later stage of fast scrolling?
Is it a special strategy to prevent the task from not being carried out for a long time? What exactly is this strategy?

**Comment by mmocny** [comment]
On the righthand side of the trace I can see a scroll event fire, and then another "yield continuation" (by the looks of the pattern).

I think that what might have happened here is not that the continuation was prioritized over the scroll event, but maybe just that the scroll event wasn't dispatched?

---

I think you might be able to look at the scroll event `timeStamp` to see if it was actually experiencing input delay?

I think if you could upload a Trace file, and/or record with Perfetto, then we might better be able to understand why this might happen.

**Comment by shaseley** [comment]
+1 to uploading a trace.

My understanding is that scroll events are rAF-aligned in Chromium, meaning they run as part of the task that produces a new frame on the main thread. But if scrolling is handled by the compositor (which might be what fast scrolling here means), main thread UI updates are actually deprioritized, in which case yield() continuations (and other tasks, e.g. setTimeout(0)) can block the next frame and scroll events.

The spec (this and HTML) allows prioritization between different task source, so this is likely a Chromium implementation/scheduling policy question/issue, so I'd suggest filing a crbug.com/new (under Chromium > Blink > Scheduling > APIs) with a (perfetto) trace or repro, and we can look at that there.

I'll close this out for now, but please do file a bug with a trace if you'd like us to take a closer look at how the policy is affecting your example.
