### ISSUE TITLE
What should happen if yield is called when then event loop's current scheduling state is null?

### ISSUE THREAD

**Issue by jakearchibald** [WICG/scheduling-apis#106]
```html
<script>
  scheduler.yield().then(() => {
    // How does this work?
  });
</script>
```

[The spec](https://wicg.github.io/scheduling-apis/#schedule-a-yield-continuation) says:

> 1. Let inheritedState be the scheduler’s [relevant agent](https://html.spec.whatwg.org/multipage/webappapis.html#relevant-agent)'s [event loop](https://html.spec.whatwg.org/multipage/webappapis.html#concept-agent-event-loop)'s [current scheduling state](https://wicg.github.io/scheduling-apis/#event-loop-current-scheduling-state).
> 2. Let abortSource be inheritedState’s [abort source](https://wicg.github.io/scheduling-apis/#scheduling-state-abort-source).

But in the above example, _inheritedState_ will be null.

**Comment by shaseley** [comment]
Thanks -- yeah that's missing a null check. In this case `abortSource` and `prioritySource` should be initialized to null.
