### ISSUE TITLE
TaskController constructor should probably take a dictionary instead of an optional priority

### ISSUE THREAD

**Issue by shaseley** [WICG/scheduling-apis#26]
The [`TaskController` constructor](https://wicg.github.io/scheduling-apis/#sec-task-controller) currently takes a single optional parameter for priority. The TAG design principles suggest [preferring dictionary parameters over primitive parameters](https://w3ctag.github.io/design-principles/#prefer-dict-to-bool) for optional parameters. Although we don't have plans right now to add more parameters, switching to a dictionary future-proofs the API at the cost of a bit of verbosity.

```js
let controller = new TaskController('background');
```
would become
```js
let controller = new TaskController({priority: 'background'});
```

**Comment by annevk** [comment]
This would also make it easier if `new AbortController()` ever gained an argument.

**Comment by shaseley** [comment]
@annevk good point.

IMO the future-proofing here is compelling, but curious if @hober has any additional thoughts from the TAG perspective since we flagged this on the TAG spec review? I'd like to go ahead and make this change, but would like to make sure ya'll to have a chance to give feedback. Thanks.
