### ISSUE TITLE
Link to the spec from appropriate places

### ISSUE THREAD

**Issue by jyasskin** [WICG/scheduling-apis#30]
https://wicg.github.io/scheduling-apis/ from e.g.

- [x] The About section of https://github.com/WICG/scheduling-apis
- [x] By https://github.com/WICG/scheduling-apis#explainer-links
- [x] https://github.com/WICG/scheduling-apis/blob/main/explainers/prioritized-post-task.md

**Comment by shaseley** [comment]
Thanks! And good timing, I'm working on an explainer cleanup pass :).
