### ISSUE TITLE
Feedback on `scheduler.yield()`. When will it be released?

### ISSUE THREAD

**Issue by verlok** [WICG/scheduling-apis#81]
Hello,
if I understood correctly, there is no scheduled date for shipping `scheduler.yield()` yet. 

I am using it to solve INP issues on our client's websites, even if I use the fallback-y function `yieldToMain`.

```js
function yieldToMain () {
  if ('scheduler' in window && 'yield' in scheduler) {
    return scheduler.yield();
  }

  return new Promise(resolve => {
    setTimeout(resolve, 0);
  });
}

async function doWork () {
  // Do some UI-related work
  await yieldToMain();
  // Do some other background-related work
}
```

Let me explain with some simplified code from an INP audit that I've run.

Executing both the `updateUI` and the `sendAnalytics` in the same function leads to an INP longer than necessary.

**Code**

```js
function setItemView() {
  updateUI();
  sendAnalytics();
}
```

**Status**

INP **110.28 ms** 

<img width="1199" alt="NoYield" src="https://github.com/WICG/scheduling-apis/assets/1127721/39ae2fa6-72c5-4aaf-917b-098b6503a189">

# How can it be fixed?

The recommendation is to yield to the main thread between the UI update and the analytics tracking. 

It can be done in 2 ways.

## Using `scheduler.yield()`

One way is to make the function `async`, then use await `scheduler.yield() ` to yield to the main thread and allow the browser to respond to user inputs.

> **Pros**: 1️⃣ the easiest to implement; 2️⃣ grants the sequence of code execution
> **Cons**: 1️⃣ the part before the `yield()` is still synchronous, thus blocking

**Code** 

```js
// yieldToMain is just a cross-browser implementation of scheduler.yield
function yieldToMain () {
  if ('scheduler' in window && 'yield' in scheduler) {
    return scheduler.yield();
  }
  return new Promise(resolve => {
    setTimeout(resolve, 0);
  });
}

async function someAction() {
	updateUI();
  await yieldToMain();
  sendAnalytics();
}
```

**Result**

INP 68.41 ms **(-40%)**

<img width="1250" alt="SchedulerYield" src="https://github.com/WICG/scheduling-apis/assets/1127721/0332c494-9361-4538-84e3-c9146e139ced">

## Using `scheduler.postTask()`

Another way to do it is by splitting the code in different functions, and schedule them with different priorities using `scheduler.postTask()`.

> Pros: 1️⃣ the fastest to yield to the main thread
> Cons: 1️⃣ harder to implement; 2️⃣ other “urgent” tasks might sneak between your tasks; 3️⃣ not easy to polyfill, needs [the scheduler polyfill](https://www.npmjs.com/package/scheduler-polyfill)

**Code** 

```js
someAction() {
	scheduler.postTask(updateUI, { priority: 'user-blocking' };
  scheduler.postTask(sendAnalytics, { priority: 'background' };
}
```

**Result**

INP 57.64 ms **(-50%)**

<img width="1062" alt="PostTask" src="https://github.com/WICG/scheduling-apis/assets/1127721/48fec262-1e9f-46f7-8d29-e4e8ff6907f8">

# Conclusion

Because of the **pros** of `scheduler.yield` and the cons of `scheduler.postTask`, my choice for yielding to the main thread is `scheduler.yield`.

So I'd like to know what's the current status of this function and if you have any plans to release it, sooner or later.
Thanks

**Comment by verlok** [comment]
A high INP will occur if the website synchronously executes heavy code (e.g. sending data) in the event handler of some user action (click, tap, keystroke).

For example, executing both the updateUI and the sendAnalytics in the same function leads to an INP longer than necessary.

**Code**

```js
function setItemView() {
  updateUI();
  sendAnalytics();
}
```

**Status**

INP 110.28 ms 

<img width="1199" alt="NoYield" src="https://github.com/WICG/scheduling-apis/assets/1127721/39ae2fa6-72c5-4aaf-917b-098b6503a189">

# How can it be fixed?

The recommendation is to yield to the main thread between the UI update and the analytics tracking. 

It can be done in 2 ways. Explanation and tests follow.

## Using `scheduler.yield()`

One way is to make the function `async`, then use await `scheduler.yield() ` to yield to the main thread and allow the browser to respond to user inputs.

> **Pros**: 1️⃣ the easiest to implement; 2️⃣ grants the sequence of code execution
> **Cons**: 1️⃣ the part before the `yield()` is still synchronous, thus blocking

**Code** 

```js
// yieldToMain is just a cross-browser implementation of scheduler.yield
function yieldToMain () {
  if ('scheduler' in window && 'yield' in scheduler) {
    return scheduler.yield();
  }
  return new Promise(resolve => {
    setTimeout(resolve, 0);
  });
}

async function someAction() {
	updateUI();
  await yieldToMain();
  sendAnalytics();
}
```

**Result**

INP 68.41 ms (-40%)

<img width="1250" alt="SchedulerYield" src="https://github.com/WICG/scheduling-apis/assets/1127721/0332c494-9361-4538-84e3-c9146e139ced">

## Using `scheduler.postTask()`

Another way to do it is by splitting the code in different functions, and schedule them with different priorities using `scheduler.postTask()`.

> Pros: 1️⃣ the fastest to yield to the main thread
> Cons: 1️⃣ harder to implement; 2️⃣ other “urgent” tasks might sneak between your tasks; 3️⃣ not easy to polyfill, needs [the scheduler polyfill](https://www.npmjs.com/package/scheduler-polyfill)

**Code** 

```js
someAction() {
	scheduler.postTask(updateUI, { priority: 'user-blocking' };
  scheduler.postTask(sendAnalytics, { priority: 'background' };
}
```

**Result**

INP 57.64 ms **(-50%)**

<img width="1062" alt="PostTask" src="https://github.com/WICG/scheduling-apis/assets/1127721/48fec262-1e9f-46f7-8d29-e4e8ff6907f8">

# Conclusion

Because of the **pros** of `scheduler.yield` and the cons of `scheduler.postTask`, my choice for yielding to the main thread is `scheduler.yield`.

**Comment by verlok** [comment]
Updated first comment with feedback

**Comment by shaseley** [comment]
> So I'd like to know what's the current status of this function and if you have any plans to release it, sooner or later.

Hi, thanks for the question.

We've recently finished running an Origin Trial and we're encouraged by the results, but there's still a fair amount of [process](https://www.chromium.org/blink/launching-features/#launch-process) that needs to play out before we can potentially ship the API (OT was step 5, but we need to do some of 4). I can't provide an exact timeline or guarantees, but we're actively working on that process now, so you should hopefully see things start to move in the near future, e.g. spec PRs, [chromestatus](https://chromestatus.com/feature/6266249336586240) updates, etc.
